# Generated by Django 5.2 on 2025-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
