# Generated by Django 5.2 on 2025-08-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
    ]
