# Generated by Django 5.2 on 2025-08-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_card_options_alter_list_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='created_at',
        ),
    ]
