# Generated by Django 5.2 on 2025-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_card_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
