# Generated by Django 5.2.3 on 2025-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_workspace_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembership',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
