# Generated by Django 5.2 on 2025-08-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_boardmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.board'),
            preserve_default=False,
        ),
    ]
