# Generated by Django 5.2 on 2025-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_boardmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
