# Generated by Django 5.2 on 2025-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_card_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
