<<<<<<< HEAD
# Generated by Django 5.2 on 2025-08-08 20:10
=======
# Generated by Django 5.2.3 on 2025-08-08 12:37
>>>>>>> 92faf1f70ac5f7bf2cb1ce02eaab705474ba0115

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_boardinvitelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
<<<<<<< HEAD
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
=======
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.list'),
        ),
>>>>>>> 92faf1f70ac5f7bf2cb1ce02eaab705474ba0115
    ]
