# Generated by Django 5.2 on 2025-08-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_boardmembership_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
