# Generated by Django 5.2 on 2025-08-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_boardmembership_board_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('card_moved', 'Card Moved'), ('card_updated', 'Card Updated'), ('comment_added', 'Comment Added'), ('due_date_changed', 'Due Date Changed')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='boards.card')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_activities_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('assignee', 'Assignee'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='assignee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('card', 'user')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='card_memberships', through='boards.CardMembership', through_fields=('card', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
