# Generated by Django 5.2 on 2025-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_card_watchers_cardactivity_cardmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
