# Generated by Django 5.2 on 2025-08-17 08:43

import auth_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to=auth_app.models.avatar_upload_to)),
                ('avatar_thumbnail', models.ImageField(blank=True, help_text='Smaller version for cards and lists (40x40)', null=True, upload_to=auth_app.models.avatar_upload_to)),
                ('banner', models.ImageField(blank=True, help_text='Profile banner image', null=True, upload_to=auth_app.models.banner_upload_to)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('is_discoverable', models.BooleanField(default=True)),
                ('show_boards_on_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
